language: python
python:
  - "3.6"
cache: pip
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libleptonica-dev libtesseract-dev tesseract-ocr
install:
  - pip install -r requirements_dev.txt
script:
  - py.test --cov-report term-missing --cov app -v